// NukeVFX — particle/VFX module entry point; model + sim + rendering live in Particles.h/.cpp.
#include <NukeVFX/Particles.h>
#include <NukeVFX/FogVolume.h>   // ScatterVolume + FogVolume: the media of the World's volumetric grid

#include <interface/NUKEEInteface.h>
#include <interface/AtomCreators.h>   // "+"-menu atom templates (editor builds the menu from this)
#include <interface/ComponentIcons.h> // viewport entity icons (editor draws from this registry)
#include <iostream>
#include <cstring>

using namespace nuke;

// Generated by the nukegen CMake prebuild; must be #included IN-TU.
#include "NukeVFX.gen.inc"   // defines NukeReflectInit_NukeVFX()

class NukeVFXModule : public NUKEModule
{
public:
	NukeVFXModule()
	{
		strcpy(title, "NukeVFX");
		strcpy(author, "Luastris");
		strcpy(version, "1.0");
		strcpy(description, "Particle VFX: emitters (billboard/stretched/trail/mesh), force fields, wind/physics interaction");
	}

	void OnLoad() override
	{
		NukeReflectInit_NukeVFX();   // ParticleEmitter / ScatterVolume / FogVolume become Add Component-able / scriptable (ForceField lives in the engine)

		RegisterAtomCreator({ "Effects", "Particle Emitter", "" /* ICON_LC_SPARKLES */, { "ParticleEmitter" } });
		RegisterComponentIcon({ "ParticleEmitter", "" /* ICON_LC_SPARKLES */, { 1.0f, 0.75f, 0.35f, 0.92f } });
		RegisterAtomCreator({ "Effects", "Scatter Volume", "" /* ICON_LC_SUN */, { "ScatterVolume" } });   // clear air that scatters the lights (rays / cones)
		RegisterAtomCreator({ "Effects", "Fog Volume", "" /* ICON_LC_CLOUD_FOG */, { "FogVolume" } });
		RegisterComponentIcon({ "FogVolume", "" /* ICON_LC_CLOUD_FOG */, { 0.78f, 0.82f, 0.9f, 0.92f } });
		RegisterComponentIcon({ "ScatterVolume", "" /* ICON_LC_SUN */, { 0.95f, 0.9f, 0.7f, 0.92f } });
		std::cout << "[NukeVFX]\tloaded" << std::endl;
	}

	void Run(AppInstance*) override {}
	void Shutdown() override { stopped = true; }
	bool HasSettings() override { return false; }
	void Settings() override {}
};

// Exported under the unmangled symbol "plugin" — the loader imports it via boost::dll.
extern "C" BOOST_SYMBOL_EXPORT NukeVFXModule plugin;
NukeVFXModule plugin;
